var Skills = {
    ALCHEMY:           0,
    ARCHERY:           1,
    ATHLETICS:         2,
    BARTER:            3,
    BLACKSMITHY:       4,
    CARPENTRY:         5,
    CONCENTRATION:     6,
    DETECTING_HIDDEN:  7,
    EVASION:           8,
    HEALING:           9,
    HERBALISM:         10,
    HIDING:            11,
    LUMBERJACKING:     12,
    MACE_FIGHTING:     13,
    MAGERY:            14,
    MAGIC_PENETRATION: 15,
    MAGIC_RESISTANCE:  16,
    MEDITATION:        17,
    MINING:            18,
    PARRYING:          19,
    SNOOPING:          20,
    STEALING:          21,
    STEALTH:           22,
    SWORDSMANSHIP:     23,
    TACTICS:           24,
    UNARMED_FIGHTING:  25,
};

module.exports = Skills;

/*
 ALCHEMY:           0,
 ARCHERY:           1,
 ATHLETICS:         2,
 BARTER:            3,
 BLACKSMITHY:       4,
 CARPENTRY:         5,
 CONCENTRATION:     6,
 DETECTING_HIDDEN:  7,
 EVASION:           8,
 HEALING:           9,
 HERBALISM:         10,
 HIDING:            11,
 LUMBERJACKING:     12,
 MACE_FIGHTING:     13,
 MAGERY:            14,
 MAGIC_PENETRATION: 15,
 MAGIC_RESISTANCE:  16,
 MEDITATION:        17,
 MINING:            18,
 PARRYING:          19,
 SNOOPING:          20,
 STEALING:          21,
 STEALTH:           22,
 SWORDSMANSHIP:     23,
 TACTICS:           24,
 UNARMED_FIGHTING:  25,
 */