package enums

type Skill int

type skills struct {
	ALCHEMY           Skill
	ARCHERY           Skill
	ATHLETICS         Skill
	BARTER            Skill
	BLACKSMITHY       Skill
	CARPENTRY         Skill
	CONCENTRATION     Skill
	DETECTING_HIDDEN  Skill
	EVASION           Skill
	HEALING           Skill
	HERBALISM         Skill
	HIDING            Skill
	LUMBERJACKING     Skill
	MACE_FIGHTING     Skill
	MAGERY            Skill
	MAGIC_PENETRATION Skill
	MAGIC_RESISTANCE  Skill
	MEDITATION        Skill
	MINING            Skill
	PARRYING          Skill
	SNOOPING          Skill
	STEALING          Skill
	STEALTH           Skill
	SWORDSMANSHIP     Skill
	TACTICS           Skill
	UNARMED_FIGHTING  Skill
}

var SKILLS skills = skills{
	ALCHEMY:           0,
	ARCHERY:           1,
	ATHLETICS:         2,
	BARTER:            3,
	BLACKSMITHY:       4,
	CARPENTRY:         5,
	CONCENTRATION:     6,
	DETECTING_HIDDEN:  7,
	EVASION:           8,
	HEALING:           9,
	HERBALISM:         10,
	HIDING:            11,
	LUMBERJACKING:     12,
	MACE_FIGHTING:     13,
	MAGERY:            14,
	MAGIC_PENETRATION: 15,
	MAGIC_RESISTANCE:  16,
	MEDITATION:        17,
	MINING:            18,
	PARRYING:          19,
	SNOOPING:          20,
	STEALING:          21,
	STEALTH:           22,
	SWORDSMANSHIP:     23,
	TACTICS:           24,
	UNARMED_FIGHTING:  25,
}

var CLASS_SKILLS = map[Class][]Skill{
	CLASSES.ROGUE: []Skill{
		SKILLS.ARCHERY,
		SKILLS.ATHLETICS,
		SKILLS.BARTER,
		SKILLS.DETECTING_HIDDEN,
		SKILLS.EVASION,
		SKILLS.HIDING,
		SKILLS.MACE_FIGHTING,
		SKILLS.MAGIC_RESISTANCE,
		SKILLS.SNOOPING,
		SKILLS.STEALING,
		SKILLS.STEALTH,
		SKILLS.SWORDSMANSHIP,
		SKILLS.TACTICS,
		SKILLS.UNARMED_FIGHTING,
	},
	CLASSES.SORCERER: []Skill{
		SKILLS.ALCHEMY,
		SKILLS.ATHLETICS,
		SKILLS.BARTER,
		SKILLS.CONCENTRATION,
		SKILLS.EVASION,
		SKILLS.HERBALISM,
		SKILLS.MAGERY,
		SKILLS.MAGIC_PENETRATION,
		SKILLS.MAGIC_RESISTANCE,
		SKILLS.MEDITATION,
	},
	CLASSES.WARRIOR: []Skill{
		SKILLS.ATHLETICS,
		SKILLS.BARTER,
		SKILLS.BLACKSMITHY,
		SKILLS.CARPENTRY,
		SKILLS.EVASION,
		SKILLS.HEALING,
		SKILLS.LUMBERJACKING,
		SKILLS.MACE_FIGHTING,
		SKILLS.MAGIC_RESISTANCE,
		SKILLS.MINING,
		SKILLS.PARRYING,
		SKILLS.SWORDSMANSHIP,
		SKILLS.TACTICS,
		SKILLS.UNARMED_FIGHTING,
	},
}
